version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: e_wallet_mysql
    environment:
      MYSQL_DATABASE: e-wallet
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Measure1234!@#$
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ewallet-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: e_wallet_sqlserver
    environment:
      ACCEPT_EULA: "yes"
      MSSQL_PID: "express"
      SA_PASSWORD: verYs3cret
    ports:
      - "1433:1433"
    networks:
      - ewallet-network

volumes:
  mysql_data:

networks:
  ewallet-network:
    driver: bridge

